# Form implementation generated from reading ui file '.\resources\activation_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 160)
        Dialog.setMinimumSize(QtCore.QSize(280, 160))
        Dialog.setMaximumSize(QtCore.QSize(280, 410))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        Dialog.setFont(font)
        Dialog.setStyleSheet(
            "background-color: rgba(36,36,36,255);\n" "color: rgb(255,255,255);"
        )
        self.FCGroup = QtWidgets.QGroupBox(parent=Dialog)
        self.FCGroup.setGeometry(QtCore.QRect(0, 0, 280, 160))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.FCGroup.setFont(font)
        self.FCGroup.setStyleSheet("border-radius: 4px;")
        self.FCGroup.setTitle("")
        self.FCGroup.setObjectName("FCGroup")
        self.ActivationButton = QtWidgets.QPushButton(parent=self.FCGroup)
        self.ActivationButton.setGeometry(QtCore.QRect(20, 80, 240, 30))
        self.ActivationButton.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 4px;\n"
            "    background-color: #2fa572; \n"
            "}\n"
            "QPushButton:hover{\n"
            "    border-radius: 4px;\n"
            "    background-color: rgba(16,106,67,255);\n"
            "}"
        )
        self.ActivationButton.setObjectName("ActivationButton")
        self.Entry = QtWidgets.QTextEdit(parent=self.FCGroup)
        self.Entry.setGeometry(QtCore.QRect(20, 40, 240, 30))
        self.Entry.setStyleSheet(
            "background-color: rgba(59,59,59,255);\n" "border-radius: 4px;"
        )
        self.Entry.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.TextEditorInteraction
        )
        self.Entry.setObjectName("Entry")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ActivationButton.setText(_translate("Dialog", "Активировать"))
        self.Entry.setPlaceholderText(_translate("Dialog", "Лицензионный ключ"))
